// <auto-generated />
using System;
using InvoiceManagerMVC.EFModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvoiceManagerMVC.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    partial class InvoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoiceManagerMVC.EFModels.Invoice", b =>
                {
                    b.Property<int>("XId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("xID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("XId"));

                    b.Property<string>("InvoiceName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("invoice_name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("XId")
                        .HasName("PK__Invoice__313C590AED48FA28");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("InvoiceManagerMVC.EFModels.InvoiceItem", b =>
                {
                    b.Property<int>("XId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("xID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("XId"));

                    b.Property<int>("AmountToPay")
                        .HasColumnType("integer")
                        .HasColumnName("amount_to_pay");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline");

                    b.Property<int>("KInvoice")
                        .HasColumnType("integer")
                        .HasColumnName("k_invoice");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("receiver");

                    b.HasKey("XId")
                        .HasName("PK__InvoiceI__313C590ACEB8958D");

                    b.HasIndex("KInvoice");

                    b.ToTable("InvoiceItem", (string)null);
                });

            modelBuilder.Entity("InvoiceManagerMVC.EFModels.InvoiceItem", b =>
                {
                    b.HasOne("InvoiceManagerMVC.EFModels.Invoice", "KInvoiceNavigation")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("KInvoice")
                        .IsRequired()
                        .HasConstraintName("FK__InvoiceIt__k_inv__267ABA7A");

                    b.Navigation("KInvoiceNavigation");
                });

            modelBuilder.Entity("InvoiceManagerMVC.EFModels.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
